---
# Add all users specified for this build

# Copy all contents from local files/etc/skel to remote /etc/skel
- name: Configure /skel files to establish baseline for all home directories
  copy: >
    src=etc/skel/
    dest=/etc/skel
    owner=root
    group=root
    mode=0644
  when: role_users_customize_skel 
  tags: 
    - role-users-skel

# Makes this role self-contained and executable without dependencies.
- name: Add baseline system groups required by users module
  group: >
    name={{ item.name }} 
    system={{ item.system }}
    state=present
  with_items: role_users_groups
  tags:
    - role-users-group-dependencies

- name: Configure all user accounts for host
  user: >
    name={{ item.username }}
    password={{ item.password }}
    groups={{ item.groups }}
    system={{ item.system }}
    createhome={{ item.createhome }}
    append=yes
  with_items: role_users_list
  tags: 
    - role-users-create-users

- name: Alias email entries for users
  lineinfile: >
      dest=/etc/aliases 
      line="{{ item.username }}: {{ item.email }}"
      state=present
  with_items: role_users_list
  when: role_users_set_aliases
  tags:
    - role-users-email-aliases
