---
# Add all users specified for this build

- name: system groups | add baseline system groups
  group: name={{ item }} state=present system=yes 
  with_items: 
    - sshusers

- name: new users | add new user
  user: name={{ item.username }} state=present password={{ item.password }} groups={{ item.groups }}
  with_items: users
  tags: 
    - user-management

- name: new users | create ssh directory for users
  file: path=/home/{{ item.username }}/.ssh state=directory owner={{ item.username }} group={{ item.username }} mode=0755
  with_items: users
  tags:
    - user-management

- name: new users | add ssh pubkey for users
  copy: content='{{ item.pubkey }}' dest=/home/{{ item.username }}/.ssh/authorized_keys owner={{ item.username }} group={{ item.username }} mode=0644
  with_items: users
  tags: 
    - user-management

- name: new users | alias email entries for users
  lineinfile: >
      dest=/etc/aliases 
      line="{{ item.username }}: {{ item.email }}"
      state=present
  with_items: users
  tags:
    - user-management
